# Generated by Django 3.2.6 on 2021-08-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_area', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('aqi_value', models.IntegerField()),
                ('aqi_category', models.CharField(max_length=50)),
            ],
        ),
    ]
