# Generated by Django 3.2.6 on 2021-08-29 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aqi_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='update_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
